kind = "mobile"
previewPath = "/crypto-mobile/"
title = "CryptoGuard Mobile"
version = "1.0.0"
id = "artifacts/crypto-mobile"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/crypto-mobile/" ]
localPort = 22995

[services.development]
run = "pnpm --filter @workspace/crypto-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/crypto-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/crypto-mobile", "run", "serve" ]

[services.env]
PORT = "22995"
BASE_PATH = "/crypto-mobile/"
